### ISSUE TITLE
Unable to watch anything 

### ISSUE THREAD

**Issue by naveenguna123** [Anistream/Anistream-Mobile#60]
It doesn't play any videos it only appear black screen. Please fix the issue

**Comment by meme-alchemist** [comment]
please stop spamming this issue

**Comment by VinodKrBhardwaj** [comment]
@meme-alchemist i have a idea brother why don't you write a message that we should not spam the app because we need to save it then every person can know and read it

**Comment by meme-alchemist** [comment]
@VinodKrBhardwaj I think another person have made one but you know people just like to write the problems without reading other posts and doesn't really care so yeah

**Comment by VinodKrBhardwaj** [comment]
@meme-alchemist thnks bro waiting for your reply as you know every one is sad about the app so they are  telling there experiencing so why don't you write it again so people will know what the problem is why you are stopping them to spam the app that will be a great help to those to and I respect you for telling the people not to spam the app I think you don't mind in writing the same things in a better way so that people can understand

**Comment by CR4KE** [comment]
Pretty sure this is a dead app for now unless someone else picks it up, I think it's open sourced here on GitHub so anyone can pick it up and fix it, but I think riku has almost definitely dropped it, it's been 2+ weeks now and not heard anything from them.

**Comment by VinodKrBhardwaj** [comment]
I think he must be busy with something as you know in this Pandemic everyone is busy with anything so we should wait and be patient he will listen to us

**Comment by memetastical** [comment]
In having the same problem also

**Comment by animeforever200323** [comment]
Please stop we all know about this existing issue
