### ISSUE TITLE
Episodes are having problem

### ISSUE THREAD

**Issue by VinodKrBhardwaj** [Anistream/Anistream-Mobile#99]
When ever I want to skip any episode it does not skip and it restarts the episode which I was watching like if I'm watching episode 33 and choose next episode the next episode does  not play rather then the episode I was currently starts again please see @Silver-Wulf

**Comment by S-lab96** [comment]
My app still isn't working
Any idea what reason might be ?
I've updated it already

**Comment by VinodKrBhardwaj** [comment]
@S-lab96 sir maybe your internet connection must be slow because when ever my connect is low it does not download properly

**Comment by VinodKrBhardwaj** [comment]
@Silver-Wulf  sir please fix the option of next episode please sir this is the best all we got 🙏🙏🙏🙏🙏

**Comment by Riku32** [comment]
On the newest update, this issue does not occur

**Comment by VinodKrBhardwaj** [comment]
Riku sir i have a screen video can you please see it

**Comment by VinodKrBhardwaj** [comment]
Please i can show you the problem

**Comment by Murphy05** [comment]
i really love this app please don't give up. I can see that you guys get a
lot of tough messages about the apps performance but for me i am able to
watch all my anime (plus hentai lol).  If you guys need any help with the
app's development I am happy to help. right now i don't have a computer for
code but later i am sure i can work something out. I am not the best at my
coding skills but definitely know somebody who may be able to help you.
just hit me up anytime after 12:00 pm (somewhere in the afternoon). Thanks
for all the hard work and development.

ps. i currently don't have the app so maybe you can send me a google file (
i have a chrome book because my last laptop broke.)
